# Generated by Django 2.0.7 on 2018-07-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completiondate', models.DateTimeField()),
                ('priority', models.CharField(choices=[('High', 'High Priority'), ('Low', 'Low Priority'), ('Normal', 'Normal Priority')], max_length=100)),
                ('iscompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
